export const icons = {
  settings: require('src/assets/icons/settings.png'),
  map: require('src/assets/icons/map.png'),
  checklist: require('src/assets/icons/checklist.png'),
  home_outline: require('src/assets/icons/home-outline.png'),
  home_fill: require('src/assets/icons/home-fill.png'),
  user_outline: require('src/assets/icons/user-outline.png'),
  user_fill: require('src/assets/icons/user-fill.png'),
  eye: require('src/assets/icons/eye.png'),
  eye_crossed: require('src/assets/icons/eye-crossed.png'),
  history: require('src/assets/icons/history.png'),
  h_three_dot: require('src/assets/icons/menu-dots.png'),
  person: require('src/assets/icons/person.png'),
  enter: require('src/assets/icons/enter.png'),
  exit: require('src/assets/icons/exit.png'),
  arrow_left: require('src/assets/icons/arrow-left.png'),
  project: require('src/assets/icons/diagram-project.png'),
  calendar: require('src/assets/icons/calendar.png'),
  arrow_down: require('src/assets/icons/arrow-down.png'),
  rotate: require('src/assets/icons/rotate-reverse.png'),
  power: require('src/assets/icons/power.png'),
  bolt: require('src/assets/icons/bolt.png'),
  bell: require('src/assets/icons/bell.png'),
  bolt_slash: require('src/assets/icons/bolt-slash.png'),
  search: require('src/assets/icons/search.png'),
  leave: require('src/assets/color-icons/leave.png'),
  payslip: require('src/assets/color-icons/payslip.png'),
  documents: require('src/assets/color-icons/documentation.png'),
  request: require('src/assets/color-icons/request.png'),
};

export type iconType = keyof typeof icons;
